# Generated by Django 3.0.3 on 2020-02-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='state',
        ),
    ]
